### ISSUE TITLE
Deployment fails due to difference in changes

### ISSUE THREAD

**Issue by Stivaros** [vitalyliber/dokku-github-action#12]
Hi, when I attempt to deploy I'm getting the following error:

```bash
The deploy is starting
Warning: Permanently added 'learning-journal.stivaros.com,18.132.177.167' (ECDSA) to the list of known hosts.
To learning-journal.stivaros.com:learning-journal
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'dokku@learning-journal.stivaros.com:learning-journal'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I've come across this error many times before when trying to push after a rebase. What's weird here, however, is that I can `git pull master` locally and then immediately `git push dokku` and it works. Additionally, `git diff origin master` is empty, when run locally.

Any thoughts please?

**Comment by vitalyliber** [comment]
@Stivaros did you try force push? I think you have some git related problems. Please investigate this https://stackoverflow.com/questions/18328800/github-updates-were-rejected-because-the-remote-contains-work-that-you-do-not-h

**Comment by vitalyliber** [comment]
@Stivaros I will close this issue
