### ISSUE TITLE
pushing to dokku behind IP restrictions

### ISSUE THREAD

**Issue by wdiechmann** [vitalyliber/dokku-github-action#22]
hi,

I'd really like to use `dokku-github-action` but I need to tell a firewall in front of the servers what IP this deployment will be coming from - -

Any ideas how to find out what IP range to allow ssh access?

**Comment by vitalyliber** [comment]
@wdiechmann good question. Thank you!

I think you can investigate that here 
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#about-self-hosted-runners

Self-hosted runner will have IP of the server where it will be hosted

**Comment by wdiechmann** [comment]
hi @vitalyliber 

thx a bunch for commenting/suggesting where to look!

this all seems quite above/beyond my paygrade 😊  I'm afraid - do you know of anyone having done this? 

use-case:

> Linux VM (Ubuntu) behind company firewall running Docker - and dokku installed - should run a number of containers (rails, redis, postgresql, etc) and preferably have new containers spun up by dokku-github-action 

may I add that the customer is ready to pay for the necessary config

**Comment by vitalyliber** [comment]
@wdiechmann I think you need to find DevOps for your goals 👌
I'm sorry but I can't help with it 😑
