### ISSUE TITLE
Deploy finding wrong Default Branch

### ISSUE THREAD

**Issue by kusky** [vitalyliber/dokku-github-action#27]
Hi, since the change about the Dubious Ownership error, we have faced an issue where our deploy process is actually not working. The issue is about the default branch line not working as it used to, even when using the v7.1. (I think it this one `DEFAULT_BRANCH="$(git remote show origin | awk '/HEAD branch/ {print $NF}')"`

This is the error that we are getting:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/13470556/220606117-90db0545-3d2b-4f75-a07c-a9cf76ebc578.png">

If I execute that line in my own machine, it does work as usual, getting main as the head branch. But when it gets triggered in Dokku on our cloud machine, it doesn't. This was working without issues until maybe 2-3 weeks ago, so we are a bit lost on what the issue could be.

Thanks!

**Comment by vitalyliber** [comment]
Hey @kusky. Please create PR If you know how to solve your issue 🙏
