### ISSUE TITLE
Public key is unnecessary

### ISSUE THREAD

**Issue by nerg4l** [vitalyliber/dokku-github-action#5]
From [ssh.com Key Pair - Public and Private](https://www.ssh.com/ssh/public-key-authentication#key-pair---public-and-private)

> A public key that is copied to the SSH server(s). [...]

Public key has to be stored on the target of the ssh connection inside `authorized_keys`

> A private key that remains (only) with the user. [...]

Private key has to be stored on the client of the ssh connection. (eg. `id_rsa`)

This means that adding `$SSH_PATH/deploy_key.pub` is completely unnecessary.

**Comment by vitalyliber** [comment]
@nerg4l thank you! I will investigate it.

**Comment by nerg4l** [comment]
My public key is an empty string here: https://github.com/broadcastt/broadcastt-docs/blob/master/.github/workflows/main.yml

As far as know I have to set it because it is set as `required: true` in `action.yml`.
